<?php
/**
 * G2A Pay payment option logo
 *
 * @category    G2A
 * @package     G2A_Pay
 * @author      G2A Team
 * @copyright   Copyright (c) 2015 G2A.COM
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<img src="<?php echo $this->getSkinUrl('images/g2apay/logo.png', array('_secure' => true)); ?>"
     alt="<?php echo Mage::helper('g2apay')->__('Pay with G2A Pay') ?>" width="192" height="39" class="v-middle"/>
