<?php
/**
 * G2A Pay payment config footer
 *
 * @category    G2A
 * @package     G2A_Pay
 * @author      G2A Team
 * @copyright   Copyright (c) 2015 G2A.COM
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div style="padding: 10px 0; margin-top: 10px; border-top: 1px solid #d8d8d8;">
    <p><?php echo Mage::helper('g2apay')->__('Current IPN url:') ?> <em><?php echo $this->getIpnUrl() ?></em></p>
    <p class="note">
        <span><?php echo Mage::helper('g2apay')->__('A new IPN url will be generated with a change of IPN secret') ?></span>
    </p>
</div>
